// <auto-generated />
using System;
using DataAccessLayer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataAccessLayer.DBContext.DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccesLayer.Entities.Assets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DeviceGroupId")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("LastModifiedOnDateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGroupId");

                    b.ToTable("Assets", "dbo");
                });

            modelBuilder.Entity("DataAccesLayer.Entities.DeviceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOnDateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("LastModifiedOnDateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("ParentDeviceGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDeviceGroupId");

                    b.ToTable("DeviceGroup", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_No_Self_Reference", "1 = case when ParentDeviceGroupId = Id then 0 else 1 end");
                        });
                });

            modelBuilder.Entity("DataAccesLayer.Entities.Assets", b =>
                {
                    b.HasOne("DataAccesLayer.Entities.DeviceGroup", "NavDeviceGroups")
                        .WithMany("NavAssets")
                        .HasForeignKey("DeviceGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NavDeviceGroups");
                });

            modelBuilder.Entity("DataAccesLayer.Entities.DeviceGroup", b =>
                {
                    b.HasOne("DataAccesLayer.Entities.DeviceGroup", "NavParentDeviceGroups")
                        .WithMany()
                        .HasForeignKey("ParentDeviceGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NavParentDeviceGroups");
                });

            modelBuilder.Entity("DataAccesLayer.Entities.DeviceGroup", b =>
                {
                    b.Navigation("NavAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
